---
- name: Add NodeSource GPG key
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /etc/apt/keyrings/nodesource.asc
    mode: "0644"

- name: Add NodeSource apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/node_22.x nodistro main"
    state: present

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: true
